version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./server/schema.sql:/usr/src/Products/server/schema.sql
      - ./newcsvs:/usr/src/Products/newcsvs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./oldcsvs:/usr/src/Products/oldcsvs
      - ./newcsvs:/usr/src/Products/newcsvs
    ports:
      - "3210:3210"
    depends_on:
      postgres:
        condition: service_healthy
